name: Create KeyVault resource

on:
  push:
    branches:
      - master
      
env:
  resourceGroupName: "rg-bicep-test"

jobs:
  deploy-bicep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure Bicep Deployment
        uses: Azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.resourceGroupName }}
          template: ./keyVault.bicep
        