name: Create KeyVault resource

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  resourceGroupName: "rg-workload-001"
  spnObjectId: 75754c6b-1bde-4306-bb1a-06a0db785528

jobs:
  deploy-bicep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure Bicep Deployment
        uses: Azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.resourceGroupName }}
          template: ./keyVault.bicep
          parameters: parSpnObjectId=${{ env.spnObjectId }}
        